//Exercise #1

When a Mule app starts, a connectivity test runs on all components that need to connect to an external server, such as the HTTP or FTP connector. If the test fails, the system will log a warning message and continue with the deployment of the app instead of blocking it.

You can modify this behavior by either setting a number of reconnection attempts after an initial failure (Reconnect) or forcing the deployment to fail when all connection attempts fail (Fail Deployment):

* Reconnect (`reconnect`): Limits the number of reconnection attempts and their execution interval. For example, you might set a count of five reconnection attempts at a frequency of every 4000 milliseconds (ms) instead of the default two reconnection attempts at a frequency of 2000 ms.
* Fail Deployment (`failsDeployment`): Forces the deployment to fail after all configured reconection attempts are exhausted.

The following example displayes the code after exhausting the five reconnection attempts:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection>
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval. For example, the default value is 2000 ms but you can set it to 4000 ms for as long as the app runs. As there is no limit on the number of attempts, the counter does not have a specified value.


The following example that doesn't have a limit on the number of reconnection attempts:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection> 
</http:request-connection>
----

